_BASE_: ./fcclip_convnext_large_eval_ade20k.yaml
MODEL:
  META_ARCHITECTURE: "MYFCCLIP"
  # backbone part.
  BACKBONE:
    NAME: "CLIP"
    FREEZE: False
  FC_CLIP:
    CLIP_MODEL_NAME: "RN50"
    CLIP_PRETRAINED_WEIGHTS: "openai"
    EMBED_DIM: 1024
    ENSEMBLE_ON_VALID_MASK: True
    USE_POOLING_WEIGHTS: False
    DIST_WEIGHT: 1
    CE_WEIGHT: 1
    LOSS: "l2"