_BASE_: ./fcclip_convnext_large_eval_ade20k.yaml
MODEL:
  META_ARCHITECTURE: "OVRCOAT"
  BACKBONE:
    NAME: "CLIP"
    FREEZE: False
  OVRCOAT:
    CE_WEIGHT: 0.1
    DIST_WEIGHT: 0.0
    RC_WEIGHTS: 0.0 # Representation compensation loss from MAFT+.
    CLIP_TRUST_WEIGHT: 0.5
    SEM_SEG_WEIGHTS: "./path" # Path to a model to load segmentation head weights from. Needs USE_PRETRAINED_SEG_HEAD_WEIGHTS=True
SOLVER:
  IMS_PER_BATCH: 9
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 1000
TRAIN:
  LOSSES: # Works only with WITH_FC_CLIP_MASKS: True . For GT masks we always use oov ce and the clip comparison loss
    - "oov_ce"
    #- "ma_loss"
    - "masks"
    - "labels"
  USE_PRETRAINED_SEG_HEAD_WEIGHTS: False # Load FC-Clip weights for the segmentation head at init
  DETACH_SEG_HEAD: False # Detach the segmentation head from the Clip backbone
TEST:
  EVAL_PERIOD: 1000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 2
DATASETS:
  TEST: ("openvocab_ade20k_panoptic_val",)