_BASE_: ./fcclip_convnext_large_eval_ade20k.yaml
MODEL:
  RECLASSIFY_VOID: False
  META_ARCHITECTURE: "RECLIP"
  # backbone part.
  BACKBONE:
    NAME: "CLIP"
    FREEZE: False
  FC_CLIP:
    CLIP_MODEL_NAME: "convnext_large_d_320"
    CLIP_PRETRAINED_WEIGHTS: "laion2b_s29b_b131k_ft_soup"
    SEM_SEG_WEIGHTS: "/home/nikolay/fcclip_cocopan.pth"
    EMBED_DIM: 768
    GEOMETRIC_ENSEMBLE_ALPHA: 0.4
    GEOMETRIC_ENSEMBLE_BETA: 0.8
    USE_POOLING_WEIGHTS: False
    DIST_WEIGHT: 0.02
    CE_WEIGHT: 2.0
    LOSS: "l2"
    DIST_WARMUP_ITERS: 0
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  STEPS: (10000, 355092)
  #MAX_ITER: 368750
  #MAX_ITER: 55000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CHECKPOINT_PERIOD: 500
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
TRAIN:
  LOSSES: # Works only with WITH_FC_CLIP_MASKS: True . For GT masks we always use oov ce and the clip comparison loss
    - "oov_ce"
    #- "ma_loss"
    - "masks"
    - "labels"
  WITH_FC_CLIP_MASKS: True # Use FC-Clip masks during training instead of gt ones
  SEG_HEAD: False # Requires WITH_FC_CLIP_MASKS. Enables tuning of seg head
  USE_TUNED_FEATURES_FOR_SEG_HEAD: True # Passes the tuned clip features to the segmentation head instead of the frozen ones
  USE_PRETRAINED_SEG_HEAD_WEIGHTS: False # Load FC-Clip weights for the segmentation head at init
  DETACH_SEG_HEAD: False # Detach the segmentation head from the Clip backbone
TEST:
  PERFECT_MASKS: False
  WITH_VOID: False
  WITH_FC_CLIP: True
  EVAL_PERIOD: 500
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 2
DATASETS:
  TEST: ("openvocab_ade20k_panoptic_val",)
  #TEST: ("openvocab_mapillary_vistas_panoptic_val",)
  #TEST: ("openvocab_cityscapes_fine_panoptic_val",)
